/* eslint-disable */
/* auto-generated by gen/generate-mcp-tools.js — do not edit */

import type { ChatApiClient } from '@1msg/sdk';
import { GENERATED_MCP_TOOLS } from './tools.generated';

function requireArg(args: Record<string, unknown>, key: string): string {
  const value = args[key];
  if (value === undefined || value === null || value === '') {
    throw new Error(`Missing required argument: ${key}`);
  }
  return String(value);
}

function optionalArg(args: Record<string, unknown>, key: string): string | undefined {
  const value = args[key];
  if (value === undefined || value === null || value === '') {
    return undefined;
  }
  return typeof value === 'string' ? value : String(value);
}

function optionalNumber(args: Record<string, unknown>, key: string): number | undefined {
  const value = args[key];
  if (value === undefined || value === null || value === '') {
    return undefined;
  }
  if (typeof value === 'number') {
    return value;
  }
  const parsed = Number(value);
  return Number.isNaN(parsed) ? undefined : parsed;
}

function requireNumber(args: Record<string, unknown>, key: string): number {
  const value = optionalNumber(args, key);
  if (value === undefined) {
    throw new Error(`Missing required argument: ${key}`);
  }
  return value;
}

function optionalBoolean(args: Record<string, unknown>, key: string): boolean | undefined {
  const value = args[key];
  if (value === undefined || value === null || value === '') {
    return undefined;
  }
  if (typeof value === 'boolean') {
    return value;
  }
  if (typeof value === 'number') {
    return value !== 0;
  }
  const normalized = String(value).trim().toLowerCase();
  if (normalized === 'true' || normalized === '1') {
    return true;
  }
  if (normalized === 'false' || normalized === '0') {
    return false;
  }
  return undefined;
}

function requireBoolean(args: Record<string, unknown>, key: string): boolean {
  const value = optionalBoolean(args, key);
  if (value === undefined) {
    throw new Error(`Missing required argument: ${key}`);
  }
  return value;
}

function optionalArray(args: Record<string, unknown>, key: string): unknown[] | undefined {
  const value = args[key];
  if (value === undefined || value === null) {
    return undefined;
  }
  if (Array.isArray(value)) {
    return value;
  }
  if (typeof value === 'string') {
    try {
      const parsed = JSON.parse(value);
      return Array.isArray(parsed) ? parsed : undefined;
    } catch {
      return undefined;
    }
  }
  return undefined;
}

function requireArray(args: Record<string, unknown>, key: string): unknown[] {
  const value = optionalArray(args, key);
  if (!value) {
    throw new Error(`Missing required argument: ${key} (expected array)`);
  }
  return value;
}

function pickArgs(args: Record<string, unknown>, keys: string[]): Record<string, unknown> {
  const picked: Record<string, unknown> = {};
  for (const key of keys) {
    if (args[key] !== undefined && args[key] !== null && args[key] !== '') {
      picked[key] = args[key];
    }
  }
  return picked;
}

const inputFieldsByTool = new Map(
  GENERATED_MCP_TOOLS.map((tool) => [tool.name, tool.inputFields]),
);

export async function invokeGeneratedTool(
  client: ChatApiClient,
  toolName: string,
  args: Record<string, unknown>,
): Promise<unknown> {
  const inputFields = inputFieldsByTool.get(toolName) ?? Object.keys(args);

  switch (toolName) {
    case 'add_template': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.templates.addTemplate(token, bodyArg as never);
    }

    case 'block_user': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.users.blockUser(token, bodyArg as never);
    }

    case 'create_commerce': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.catalog.createCommerce(token, bodyArg as never);
    }

    case 'create_flows': {
      const token = client.config.token;
      const wabaAccountId = optionalArg(args, 'wabaAccountId');
      return client.flows.createFlows(token, wabaAccountId);
    }

    case 'create_flows_flow_id_deprecate': {
      const token = client.config.token;
      const flowId = requireArg(args, 'flowId');
      const wabaAccountId = optionalArg(args, 'wabaAccountId');
      return client.flows.createFlowsFlowIdDeprecate(flowId, token, wabaAccountId);
    }

    case 'create_flows_flow_id_publish': {
      const token = client.config.token;
      const flowId = requireArg(args, 'flowId');
      const wabaAccountId = optionalArg(args, 'wabaAccountId');
      return client.flows.createFlowsFlowIdPublish(flowId, token, wabaAccountId);
    }

    case 'create_groups': {
      const token = client.config.token;
      return client.groups.createGroups(token);
    }

    case 'create_groups_group_id': {
      const token = client.config.token;
      const groupId = requireArg(args, 'groupId');
      return client.groups.createGroupsGroupId(groupId, token);
    }

    case 'create_groups_group_id_invitelink': {
      const token = client.config.token;
      const groupId = requireArg(args, 'groupId');
      return client.groups.createGroupsGroupIdInvitelink(groupId, token);
    }

    case 'create_read_message': {
      const token = client.config.token;
      const messageId = optionalArg(args, 'messageId');
      const msgId = optionalArg(args, 'msgId');
      const typingIndicator = optionalBoolean(args, 'typingIndicator');
      return client.messaging.createReadMessage(token, messageId, msgId, typingIndicator);
    }

    case 'create_upload_media': {
      const token = client.config.token;
      const bodyArg = (args.payload ?? args) as Record<string, unknown>;
      return client.messaging.createUploadMedia(token, Object.keys(bodyArg).length > 0 ? bodyArg : undefined);
    }

    case 'delete_flows_flow_id': {
      const token = client.config.token;
      const flowId = requireArg(args, 'flowId');
      const wabaAccountId = optionalArg(args, 'wabaAccountId');
      return client.flows.deleteFlowsFlowId(flowId, token, wabaAccountId);
    }

    case 'delete_groups_group_id': {
      const token = client.config.token;
      const groupId = requireArg(args, 'groupId');
      return client.groups.deleteGroupsGroupId(groupId, token);
    }

    case 'delete_media': {
      const token = client.config.token;
      const mediaId = requireArg(args, 'mediaId');
      return client.messaging.deleteMedia(mediaId, token);
    }

    case 'delete_media_legacy': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.messaging.deleteMediaLegacy(token, bodyArg as never);
    }

    case 'get_calling_settings': {
      const token = client.config.token;
      return client.calling.getCallingSettings(token);
    }

    case 'get_commerce': {
      const token = client.config.token;
      return client.catalog.getCommerce(token);
    }

    case 'get_conversational_automation': {
      const token = client.config.token;
      return client.channel.getConversationalAutomation(token);
    }

    case 'get_flows_flow_id': {
      const token = client.config.token;
      const flowId = requireArg(args, 'flowId');
      const wabaAccountId = optionalArg(args, 'wabaAccountId');
      return client.flows.getFlowsFlowId(flowId, token, wabaAccountId);
    }

    case 'get_flows_flow_id_preview': {
      const token = client.config.token;
      const flowId = requireArg(args, 'flowId');
      const wabaAccountId = optionalArg(args, 'wabaAccountId');
      return client.flows.getFlowsFlowIdPreview(flowId, token, wabaAccountId);
    }

    case 'get_groups_group_id': {
      const token = client.config.token;
      const groupId = requireArg(args, 'groupId');
      return client.groups.getGroupsGroupId(groupId, token);
    }

    case 'get_groups_group_id_invitelink': {
      const token = client.config.token;
      const groupId = requireArg(args, 'groupId');
      return client.groups.getGroupsGroupIdInvitelink(groupId, token);
    }

    case 'get_me': {
      const token = client.config.token;
      return client.profile.getMe(token);
    }

    case 'get_mm_lite_status': {
      const token = client.config.token;
      return client.messaging.getMmLiteStatus(token);
    }

    case 'get_status': {
      const token = client.config.token;
      return client.channel.getStatus(token);
    }

    case 'get_webhook': {
      const token = client.config.token;
      return client.webhooks.getWebhook(token);
    }

    case 'get_whatsapp_business_encryption': {
      const token = client.config.token;
      return client.flows.getWhatsappBusinessEncryption(token);
    }

    case 'initiate_call': {
      const token = client.config.token;
      const bodyArg = (args.payload ?? args) as Record<string, unknown>;
      return client.calling.initiateCall(token, bodyArg as never);
    }

    case 'list_blocked_users': {
      const token = client.config.token;
      return client.users.listBlockedUsers(token);
    }

    case 'list_flows': {
      const token = client.config.token;
      const wabaAccountId = optionalArg(args, 'wabaAccountId');
      return client.flows.listFlows(token, wabaAccountId);
    }

    case 'list_groups': {
      const token = client.config.token;
      return client.groups.listGroups(token);
    }

    case 'list_messages': {
      const token = client.config.token;
      return client.messaging.listMessages(token);
    }

    case 'list_templates': {
      const token = client.config.token;
      return client.templates.listTemplates(token);
    }

    case 'patch_flows_flow_id_assets': {
      const token = client.config.token;
      const flowId = requireArg(args, 'flowId');
      const wabaAccountId = optionalArg(args, 'wabaAccountId');
      return client.flows.patchFlowsFlowIdAssets(flowId, token, wabaAccountId);
    }

    case 'patch_flows_flow_id_metadata': {
      const token = client.config.token;
      const flowId = requireArg(args, 'flowId');
      const wabaAccountId = optionalArg(args, 'wabaAccountId');
      return client.flows.patchFlowsFlowIdMetadata(flowId, token, wabaAccountId);
    }

    case 'remove_template': {
      const token = client.config.token;
      const bodyArg = (args.payload ?? args) as Record<string, unknown>;
      return client.templates.removeTemplate(token, bodyArg as never);
    }

    case 'retrieve_media': {
      const token = client.config.token;
      const mediaId = requireArg(args, 'mediaId');
      return client.messaging.retrieveMedia(token, mediaId);
    }

    case 'send_address_message': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.messaging.sendAddressMessage(token, bodyArg as never);
    }

    case 'send_button': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.messaging.sendButton(token, Object.keys(bodyArg).length > 0 ? bodyArg : undefined);
    }

    case 'send_carousel': {
      const token = client.config.token;
      const params = requireArray(args, 'params') as object[];
      const body = optionalArg(args, 'body');
      const quotedMsgId = optionalArg(args, 'quotedMsgId');
      const chatId = optionalArg(args, 'chatId');
      const phone = optionalNumber(args, 'phone');
      return client.messaging.sendCarousel(token, params, body, quotedMsgId, chatId, phone);
    }

    case 'send_contact': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.messaging.sendContact(token, Object.keys(bodyArg).length > 0 ? bodyArg : undefined);
    }

    case 'send_cta_url': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.messaging.sendCtaUrl(token, bodyArg as never);
    }

    case 'send_file': {
      const token = client.config.token;
      const body = optionalArg(args, 'body');
      const filename = optionalArg(args, 'filename');
      const mediaId = optionalArg(args, 'mediaId');
      const mediaType = optionalArg(args, 'mediaType') as never;
      const voice = optionalBoolean(args, 'voice');
      const caption = optionalArg(args, 'caption');
      const quotedMsgId = optionalArg(args, 'quotedMsgId');
      const chatId = optionalArg(args, 'chatId');
      const phone = optionalNumber(args, 'phone');
      return client.messaging.sendFile(token, body, filename, mediaId, mediaType, voice, caption, quotedMsgId, chatId, phone);
    }

    case 'send_flow': {
      const token = client.config.token;
      const body = requireArg(args, 'body');
      const flowId = requireArg(args, 'flowId');
      const flowToken = requireArg(args, 'flowToken');
      const flowCta = requireArg(args, 'flowCta');
      const header = args.header as Record<string, unknown> | undefined;
      const footer = optionalArg(args, 'footer');
      const flowAction = args.flowAction as string | undefined;
      const flowActionPayload = args.flowActionPayload as object | undefined;
      const flowMessageVersion = optionalArg(args, 'flowMessageVersion');
      const mode = args.mode as string | undefined;
      const flowActionData = args.flowActionData as object | undefined;
      const flowActionScreen = optionalArg(args, 'flowActionScreen');
      const quotedMsgId = optionalArg(args, 'quotedMsgId');
      const chatId = optionalArg(args, 'chatId');
      const phone = optionalNumber(args, 'phone');
      return client.messaging.sendFlow(token, body, flowId, flowToken, flowCta, header as never, footer, flowAction as never, flowActionPayload, flowMessageVersion, mode as never, flowActionData, flowActionScreen, quotedMsgId, chatId, phone);
    }

    case 'send_list': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.messaging.sendList(token, Object.keys(bodyArg).length > 0 ? bodyArg : undefined);
    }

    case 'send_location': {
      const token = client.config.token;
      const lat = requireArg(args, 'lat');
      const lng = requireArg(args, 'lng');
      const address = optionalArg(args, 'address');
      const name = optionalArg(args, 'name');
      const quotedMsgId = optionalArg(args, 'quotedMsgId');
      const chatId = optionalArg(args, 'chatId');
      const phone = optionalNumber(args, 'phone');
      return client.messaging.sendLocation(token, lat, lng, address, name, quotedMsgId, chatId, phone);
    }

    case 'send_location_request': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.messaging.sendLocationRequest(token, Object.keys(bodyArg).length > 0 ? bodyArg : undefined);
    }

    case 'send_message': {
      const token = client.config.token;
      const body = requireArg(args, 'body');
      const quotedMsgId = optionalArg(args, 'quotedMsgId');
      const chatId = optionalArg(args, 'chatId');
      const phone = optionalNumber(args, 'phone');
      return client.sendMessage({ body, quotedMsgId, chatId, phone });
    }

    case 'send_order_details': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.messaging.sendOrderDetails(token, bodyArg as never);
    }

    case 'send_payment_request': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.messaging.sendPaymentRequest(token, bodyArg as never);
    }

    case 'send_product': {
      const token = client.config.token;
      const bodyArg = (args.payload ?? args) as Record<string, unknown>;
      return client.messaging.sendProduct(token, Object.keys(bodyArg).length > 0 ? bodyArg : undefined);
    }

    case 'send_reaction': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.messaging.sendReaction(token, Object.keys(bodyArg).length > 0 ? bodyArg : undefined);
    }

    case 'send_sticker': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.messaging.sendSticker(token, bodyArg as never);
    }

    case 'send_template': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.templates.sendTemplate(token, Object.keys(bodyArg).length > 0 ? bodyArg : undefined);
    }

    case 'set_conversational_automation': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.channel.setConversationalAutomation(token, bodyArg as never);
    }

    case 'set_webhook': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.webhooks.setWebhook(token, bodyArg as never);
    }

    case 'set_whatsapp_business_encryption': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.flows.setWhatsappBusinessEncryption(token, bodyArg as never);
    }

    case 'unblock_user': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.users.unblockUser(token, bodyArg as never);
    }

    case 'update_calling_settings': {
      const token = client.config.token;
      const bodyArg = (args.payload ?? args) as Record<string, unknown>;
      return client.calling.updateCallingSettings(token, bodyArg as never);
    }

    case 'update_me': {
      const token = client.config.token;
      const bodyArg = pickArgs(args, inputFields);
      return client.profile.updateMe(token, bodyArg as never);
    }
    default:
      throw new Error(`Unknown tool: ${toolName}`);
  }
}
