/* eslint-disable */
/* auto-generated by gen/generate-mcp-tools.js — do not edit */

export interface JsonSchema {
  type?: string | string[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  description?: string;
  additionalProperties?: boolean | JsonSchema;
  enum?: unknown[];
  oneOf?: JsonSchema[];
  format?: string;
  minimum?: number;
  maximum?: number;
  minLength?: number;
  maxLength?: number;
  pattern?: string;
  [key: string]: unknown;
}

export interface GeneratedMcpTool {
  /** MCP tool name (snake_case) */
  name: string;
  /** OpenAPI operationId */
  operationId: string;
  description: string;
  inputSchema: JsonSchema;
  inputFields: string[];
}

export const GENERATED_MCP_TOOLS: GeneratedMcpTool[] = [
  {
    "name": "add_template",
    "operationId": "addTemplate",
    "description": "Create message template",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "category": {
          "type": "string"
        },
        "language": {
          "type": "string"
        },
        "components": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true
          }
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "name",
      "category",
      "language",
      "components"
    ]
  },
  {
    "name": "block_user",
    "operationId": "blockUser",
    "description": "Block WhatsApp user",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "phone"
      ]
    },
    "inputFields": [
      "phone"
    ]
  },
  {
    "name": "create_commerce",
    "operationId": "createCommerce",
    "description": "Set Commerce Settings",
    "inputSchema": {
      "type": "object",
      "properties": {
        "params": {
          "type": "object",
          "required": [
            "is_cart_enabled",
            "is_catalog_visible"
          ],
          "properties": {
            "is_cart_enabled": {
              "type": "boolean",
              "description": "Enable cart"
            },
            "is_catalog_visible": {
              "type": "boolean",
              "description": "Show catalog storefront icon"
            }
          },
          "additionalProperties": true
        }
      },
      "additionalProperties": false,
      "required": [
        "params"
      ]
    },
    "inputFields": [
      "params"
    ]
  },
  {
    "name": "create_flows",
    "operationId": "createFlows",
    "description": "Create Flow",
    "inputSchema": {
      "type": "object",
      "properties": {
        "wabaAccountId": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "wabaAccountId"
    ]
  },
  {
    "name": "create_flows_flow_id_deprecate",
    "operationId": "createFlowsFlowIdDeprecate",
    "description": "Deprecate Flow",
    "inputSchema": {
      "type": "object",
      "properties": {
        "flowId": {
          "type": "string",
          "description": "Flow ID"
        },
        "wabaAccountId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "flowId"
      ]
    },
    "inputFields": [
      "flowId",
      "wabaAccountId"
    ]
  },
  {
    "name": "create_flows_flow_id_publish",
    "operationId": "createFlowsFlowIdPublish",
    "description": "Publish Flow",
    "inputSchema": {
      "type": "object",
      "properties": {
        "flowId": {
          "type": "string",
          "description": "Flow ID"
        },
        "wabaAccountId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "flowId"
      ]
    },
    "inputFields": [
      "flowId",
      "wabaAccountId"
    ]
  },
  {
    "name": "create_groups",
    "operationId": "createGroups",
    "description": "Create Group",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "create_groups_group_id",
    "operationId": "createGroupsGroupId",
    "description": "Update Group Info",
    "inputSchema": {
      "type": "object",
      "properties": {
        "groupId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "groupId"
      ]
    },
    "inputFields": [
      "groupId"
    ]
  },
  {
    "name": "create_groups_group_id_invitelink",
    "operationId": "createGroupsGroupIdInvitelink",
    "description": "Reset Invite Link",
    "inputSchema": {
      "type": "object",
      "properties": {
        "groupId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "groupId"
      ]
    },
    "inputFields": [
      "groupId"
    ]
  },
  {
    "name": "create_read_message",
    "operationId": "createReadMessage",
    "description": "Mark message as read",
    "inputSchema": {
      "type": "object",
      "properties": {
        "messageId": {
          "type": "string"
        },
        "msgId": {
          "type": "string"
        },
        "typingIndicator": {
          "type": "boolean",
          "default": false,
          "description": "Show WhatsApp typing indicator (max 25s or until reply)"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "messageId",
      "msgId",
      "typingIndicator"
    ]
  },
  {
    "name": "create_upload_media",
    "operationId": "createUploadMedia",
    "description": "Upload media",
    "inputSchema": {
      "type": "object",
      "properties": {
        "payload": {
          "type": "object",
          "additionalProperties": true,
          "description": "Request body payload"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "payload"
    ]
  },
  {
    "name": "delete_flows_flow_id",
    "operationId": "deleteFlowsFlowId",
    "description": "Delete Flow",
    "inputSchema": {
      "type": "object",
      "properties": {
        "flowId": {
          "type": "string",
          "description": "Flow ID"
        },
        "wabaAccountId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "flowId"
      ]
    },
    "inputFields": [
      "flowId",
      "wabaAccountId"
    ]
  },
  {
    "name": "delete_groups_group_id",
    "operationId": "deleteGroupsGroupId",
    "description": "Delete Group",
    "inputSchema": {
      "type": "object",
      "properties": {
        "groupId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "groupId"
      ]
    },
    "inputFields": [
      "groupId"
    ]
  },
  {
    "name": "delete_media",
    "operationId": "deleteMedia",
    "description": "Delete media from WABA storage",
    "inputSchema": {
      "type": "object",
      "properties": {
        "mediaId": {
          "type": "string",
          "description": "Numeric WABA media id"
        }
      },
      "additionalProperties": false,
      "required": [
        "mediaId"
      ]
    },
    "inputFields": [
      "mediaId"
    ]
  },
  {
    "name": "delete_media_legacy",
    "operationId": "deleteMediaLegacy",
    "description": "Delete media from WABA storage (deprecated alias)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "mediaId": {
          "type": "string",
          "description": "Numeric WABA media id"
        }
      },
      "additionalProperties": false,
      "required": [
        "mediaId"
      ]
    },
    "inputFields": [
      "mediaId"
    ]
  },
  {
    "name": "get_calling_settings",
    "operationId": "getCallingSettings",
    "description": "Get calling settings",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "get_commerce",
    "operationId": "getCommerce",
    "description": "Get Commerce Settings",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "get_conversational_automation",
    "operationId": "getConversationalAutomation",
    "description": "Get conversational automation settings",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "get_flows_flow_id",
    "operationId": "getFlowsFlowId",
    "description": "Get Flow Details",
    "inputSchema": {
      "type": "object",
      "properties": {
        "flowId": {
          "type": "string",
          "description": "Flow ID"
        },
        "wabaAccountId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "flowId"
      ]
    },
    "inputFields": [
      "flowId",
      "wabaAccountId"
    ]
  },
  {
    "name": "get_flows_flow_id_preview",
    "operationId": "getFlowsFlowIdPreview",
    "description": "Preview Flow",
    "inputSchema": {
      "type": "object",
      "properties": {
        "flowId": {
          "type": "string",
          "description": "Flow ID"
        },
        "wabaAccountId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "flowId"
      ]
    },
    "inputFields": [
      "flowId",
      "wabaAccountId"
    ]
  },
  {
    "name": "get_groups_group_id",
    "operationId": "getGroupsGroupId",
    "description": "Get Group Info",
    "inputSchema": {
      "type": "object",
      "properties": {
        "groupId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "groupId"
      ]
    },
    "inputFields": [
      "groupId"
    ]
  },
  {
    "name": "get_groups_group_id_invitelink",
    "operationId": "getGroupsGroupIdInvitelink",
    "description": "Get Invite Link",
    "inputSchema": {
      "type": "object",
      "properties": {
        "groupId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "groupId"
      ]
    },
    "inputFields": [
      "groupId"
    ]
  },
  {
    "name": "get_me",
    "operationId": "getMe",
    "description": "Get Profile Info",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "get_mm_lite_status",
    "operationId": "getMmLiteStatus",
    "description": "Get MM Lite availability and status",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "get_status",
    "operationId": "getStatus",
    "description": "Get channel status",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "get_webhook",
    "operationId": "getWebhook",
    "description": "Get webhook URL",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "get_whatsapp_business_encryption",
    "operationId": "getWhatsappBusinessEncryption",
    "description": "Get business encryption public key",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "initiate_call",
    "operationId": "initiateCall",
    "description": "Initiate WhatsApp call",
    "inputSchema": {
      "type": "object",
      "properties": {
        "payload": {
          "type": "object",
          "additionalProperties": true,
          "description": "Request body payload"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "payload"
    ]
  },
  {
    "name": "list_blocked_users",
    "operationId": "listBlockedUsers",
    "description": "List blocked WhatsApp users",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "list_flows",
    "operationId": "listFlows",
    "description": "List Flows",
    "inputSchema": {
      "type": "object",
      "properties": {
        "wabaAccountId": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "wabaAccountId"
    ]
  },
  {
    "name": "list_groups",
    "operationId": "listGroups",
    "description": "Get Groups List",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "list_messages",
    "operationId": "listMessages",
    "description": "Get messages list",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "list_templates",
    "operationId": "listTemplates",
    "description": "Get templates list",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "patch_flows_flow_id_assets",
    "operationId": "patchFlowsFlowIdAssets",
    "description": "Update Flow Structure",
    "inputSchema": {
      "type": "object",
      "properties": {
        "flowId": {
          "type": "string",
          "description": "Flow ID"
        },
        "wabaAccountId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "flowId"
      ]
    },
    "inputFields": [
      "flowId",
      "wabaAccountId"
    ]
  },
  {
    "name": "patch_flows_flow_id_metadata",
    "operationId": "patchFlowsFlowIdMetadata",
    "description": "Update Flow Metadata",
    "inputSchema": {
      "type": "object",
      "properties": {
        "flowId": {
          "type": "string",
          "description": "Flow ID"
        },
        "wabaAccountId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "flowId"
      ]
    },
    "inputFields": [
      "flowId",
      "wabaAccountId"
    ]
  },
  {
    "name": "remove_template",
    "operationId": "removeTemplate",
    "description": "Remove message template",
    "inputSchema": {
      "type": "object",
      "properties": {
        "payload": {
          "type": "object",
          "additionalProperties": true,
          "description": "Request body payload"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "payload"
    ]
  },
  {
    "name": "retrieve_media",
    "operationId": "retrieveMedia",
    "description": "Retrieve uploaded media metadata",
    "inputSchema": {
      "type": "object",
      "properties": {
        "mediaId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "mediaId"
      ]
    },
    "inputFields": [
      "mediaId"
    ]
  },
  {
    "name": "send_address_message",
    "operationId": "sendAddressMessage",
    "description": "Send address request message",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "integer"
        },
        "chatId": {
          "type": "string"
        },
        "body": {
          "type": "string",
          "description": "Body text shown with the address request"
        },
        "quotedMsgId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "body"
      ]
    },
    "inputFields": [
      "phone",
      "chatId",
      "body",
      "quotedMsgId"
    ]
  },
  {
    "name": "send_button",
    "operationId": "sendButton",
    "description": "Send Reply Buttons Message",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "string"
        },
        "body": {
          "type": "string"
        },
        "footer": {
          "type": "string"
        },
        "sections": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "reply": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string",
                    "format": "utc-millisec"
                  },
                  "title": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "phone",
      "body",
      "footer",
      "sections"
    ]
  },
  {
    "name": "send_carousel",
    "operationId": "sendCarousel",
    "description": "Send Carousel",
    "inputSchema": {
      "type": "object",
      "properties": {
        "body": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {
            "type": "object"
          }
        },
        "quotedMsgId": {
          "type": "string"
        },
        "chatId": {
          "type": "string"
        },
        "phone": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "params"
      ]
    },
    "inputFields": [
      "body",
      "params",
      "quotedMsgId",
      "chatId",
      "phone"
    ]
  },
  {
    "name": "send_contact",
    "operationId": "sendContact",
    "description": "Send a Contact",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "string"
        },
        "contacts": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "object",
                "properties": {
                  "formatted_name": {
                    "type": "string"
                  },
                  "first_name": {
                    "type": "string"
                  },
                  "last_name": {
                    "type": "string"
                  },
                  "middle_name": {
                    "type": "string"
                  },
                  "suffix": {
                    "type": "string"
                  },
                  "prefix": {
                    "type": "string"
                  }
                }
              },
              "birthday": {
                "type": "string"
              },
              "addresses": {
                "type": "array",
                "items": {}
              },
              "emails": {
                "type": "array",
                "items": {}
              },
              "org": {
                "type": "object",
                "properties": {
                  "company": {
                    "type": "string"
                  },
                  "department": {
                    "type": "string"
                  },
                  "title": {
                    "type": "string"
                  }
                }
              },
              "phones": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "phone": {
                      "type": "string",
                      "format": "utc-millisec"
                    },
                    "type": {
                      "type": "string"
                    },
                    "wa_id": {
                      "type": "string"
                    }
                  }
                }
              },
              "urls": {
                "type": "array",
                "items": {}
              }
            }
          }
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "phone",
      "contacts"
    ]
  },
  {
    "name": "send_cta_url",
    "operationId": "sendCtaUrl",
    "description": "Send CTA URL interactive message",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "integer"
        },
        "chatId": {
          "type": "string"
        },
        "body": {
          "type": "string"
        },
        "displayText": {
          "type": "string",
          "description": "Button label"
        },
        "url": {
          "type": "string",
          "format": "uri"
        },
        "header": {
          "type": "object",
          "additionalProperties": true
        },
        "footer": {
          "type": "string"
        },
        "quotedMsgId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "body",
        "displayText",
        "url"
      ]
    },
    "inputFields": [
      "phone",
      "chatId",
      "body",
      "displayText",
      "url",
      "header",
      "footer",
      "quotedMsgId"
    ]
  },
  {
    "name": "send_file",
    "operationId": "sendFile",
    "description": "Send a File",
    "inputSchema": {
      "type": "object",
      "properties": {
        "body": {
          "type": "string",
          "description": "File source (required unless mediaId is set):\n- HTTP/HTTPS URL\n- Base64 data URI\n"
        },
        "filename": {
          "type": "string",
          "description": "File name with extension (required with body, not with mediaId)"
        },
        "mediaId": {
          "type": "string",
          "description": "WABA media id from uploadMedia (alternative to body)"
        },
        "mediaType": {
          "type": "string",
          "enum": [
            "image",
            "video",
            "audio",
            "document"
          ],
          "description": "Required when using mediaId"
        },
        "voice": {
          "type": "boolean",
          "description": "Native WhatsApp voice note (audio/ogg only)"
        },
        "caption": {
          "type": "string",
          "maxLength": 1024
        },
        "quotedMsgId": {
          "type": "string"
        },
        "chatId": {
          "type": "string"
        },
        "phone": {
          "type": "integer"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "body",
      "filename",
      "mediaId",
      "mediaType",
      "voice",
      "caption",
      "quotedMsgId",
      "chatId",
      "phone"
    ]
  },
  {
    "name": "send_flow",
    "operationId": "sendFlow",
    "description": "Send WhatsApp Flow Message",
    "inputSchema": {
      "type": "object",
      "properties": {
        "body": {
          "type": "string"
        },
        "header": {
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "object"
            }
          ]
        },
        "footer": {
          "type": "string"
        },
        "flowId": {
          "type": "string"
        },
        "flowToken": {
          "type": "string"
        },
        "flowCta": {
          "type": "string"
        },
        "flowAction": {
          "type": "string",
          "enum": [
            "navigate",
            "data_exchange"
          ]
        },
        "flowActionPayload": {
          "type": "object"
        },
        "flowMessageVersion": {
          "type": "string"
        },
        "mode": {
          "type": "string",
          "enum": [
            "draft",
            "published"
          ]
        },
        "flowActionData": {
          "type": "object"
        },
        "flowActionScreen": {
          "type": "string"
        },
        "quotedMsgId": {
          "type": "string"
        },
        "chatId": {
          "type": "string"
        },
        "phone": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "body",
        "flowId",
        "flowToken",
        "flowCta"
      ]
    },
    "inputFields": [
      "body",
      "header",
      "footer",
      "flowId",
      "flowToken",
      "flowCta",
      "flowAction",
      "flowActionPayload",
      "flowMessageVersion",
      "mode",
      "flowActionData",
      "flowActionScreen",
      "quotedMsgId",
      "chatId",
      "phone"
    ]
  },
  {
    "name": "send_list",
    "operationId": "sendList",
    "description": "Send List Message",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "string"
        },
        "body": {
          "type": "string"
        },
        "buttonText": {
          "type": "string"
        },
        "action": {
          "type": "string"
        },
        "sections": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "title": {
                "type": "string"
              },
              "rows": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "format": "utc-millisec"
                    },
                    "title": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "phone",
      "body",
      "buttonText",
      "action",
      "sections"
    ]
  },
  {
    "name": "send_location",
    "operationId": "sendLocation",
    "description": "Send a Location",
    "inputSchema": {
      "type": "object",
      "properties": {
        "lat": {
          "type": "string"
        },
        "lng": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "quotedMsgId": {
          "type": "string"
        },
        "chatId": {
          "type": "string"
        },
        "phone": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "lat",
        "lng"
      ]
    },
    "inputFields": [
      "lat",
      "lng",
      "address",
      "name",
      "quotedMsgId",
      "chatId",
      "phone"
    ]
  },
  {
    "name": "send_location_request",
    "operationId": "sendLocationRequest",
    "description": "Send Location Request Message",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "string"
        },
        "body": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "phone",
      "body"
    ]
  },
  {
    "name": "send_message",
    "operationId": "sendMessage",
    "description": "Send a Message",
    "inputSchema": {
      "type": "object",
      "properties": {
        "body": {
          "type": "string",
          "description": "Message text, UTF-8 or UTF-16 string with emoji",
          "minLength": 1,
          "maxLength": 4096,
          "example": "Hello World 🌍"
        },
        "quotedMsgId": {
          "type": "string",
          "description": "Message ID to quote/reply to (Cloud API wamid)",
          "pattern": "^wamid\\..+$",
          "example": "wamid.HBgNMTIwMjA3MjEzNjkVAgARGBI5RTBCNUY0QUE2RjZBQzhGNDkA"
        },
        "chatId": {
          "type": "string",
          "description": "Chat ID in format: phone@c.us (individual) or phone@g.us (group)",
          "pattern": "^[0-9]+@[cg]\\.us$",
          "example": "12020721369@c.us"
        },
        "phone": {
          "type": "integer",
          "description": "Phone number starting with country code (alternative to chatId)",
          "minimum": 1000000000,
          "maximum": 999999999999999,
          "example": 12020721369
        }
      },
      "additionalProperties": false,
      "required": [
        "body"
      ]
    },
    "inputFields": [
      "body",
      "quotedMsgId",
      "chatId",
      "phone"
    ]
  },
  {
    "name": "send_order_details",
    "operationId": "sendOrderDetails",
    "description": "Send order details (India payments template)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "integer",
          "description": "Recipient phone (India E.164 digits, no +)"
        },
        "chatId": {
          "type": "string",
          "description": "Recipient chatId (phone@c.us / bsuid@lid / …)"
        },
        "template": {
          "type": "string",
          "description": "Approved template name with ORDER_DETAILS button"
        },
        "namespace": {
          "type": "string",
          "description": "Template namespace"
        },
        "language": {
          "type": "object",
          "description": "Template language object, e.g. code \"en\" or policy \"deterministic\" with code \"en\".\n",
          "additionalProperties": true
        },
        "params": {
          "type": "array",
          "description": "Extra template components (header/body). An order_details button is appended automatically if missing.\n",
          "items": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "order": {
          "type": "object",
          "description": "Order object (items, subtotal, tax, shipping, discount, status) per Meta Payments India docs.\n",
          "additionalProperties": true
        },
        "referenceId": {
          "type": "string",
          "description": "Unique order/payment reference id"
        },
        "paymentSettings": {
          "type": "object",
          "description": "Optional payment_settings (UPI / payment gateway / payment link).\n",
          "additionalProperties": true
        },
        "currency": {
          "type": "string",
          "description": "Currency code (INR for India)",
          "example": "INR"
        }
      },
      "additionalProperties": false,
      "required": [
        "template",
        "namespace",
        "language",
        "order"
      ]
    },
    "inputFields": [
      "phone",
      "chatId",
      "template",
      "namespace",
      "language",
      "params",
      "order",
      "referenceId",
      "paymentSettings",
      "currency"
    ]
  },
  {
    "name": "send_payment_request",
    "operationId": "sendPaymentRequest",
    "description": "Send payment request (regional)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "integer"
        },
        "region": {
          "type": "string",
          "enum": [
            "IN",
            "SG",
            "BR"
          ]
        },
        "body": {
          "type": "string"
        },
        "interactive": {
          "type": "object",
          "additionalProperties": true
        },
        "action": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "additionalProperties": false,
      "required": [
        "phone",
        "region"
      ]
    },
    "inputFields": [
      "phone",
      "region",
      "body",
      "interactive",
      "action"
    ]
  },
  {
    "name": "send_product",
    "operationId": "sendProduct",
    "description": "Send a Product",
    "inputSchema": {
      "type": "object",
      "properties": {
        "payload": {
          "type": "object",
          "additionalProperties": true,
          "description": "Request body payload"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "payload"
    ]
  },
  {
    "name": "send_reaction",
    "operationId": "sendReaction",
    "description": "Send Reaction",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "string"
        },
        "body": {
          "type": "string"
        },
        "quotedMsgId": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "phone",
      "body",
      "quotedMsgId"
    ]
  },
  {
    "name": "send_sticker",
    "operationId": "sendSticker",
    "description": "Send sticker message",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "integer"
        },
        "chatId": {
          "type": "string"
        },
        "mediaId": {
          "type": "string",
          "description": "WABA media id from uploadMedia"
        },
        "link": {
          "type": "string",
          "description": "Public URL to webp sticker"
        },
        "quotedMsgId": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "phone",
      "chatId",
      "mediaId",
      "link",
      "quotedMsgId"
    ]
  },
  {
    "name": "send_template",
    "operationId": "sendTemplate",
    "description": "Send Template Message",
    "inputSchema": {
      "type": "object",
      "properties": {
        "template": {
          "type": "string"
        },
        "language": {
          "type": "object",
          "properties": {
            "policy": {
              "type": "string"
            },
            "code": {
              "type": "string"
            }
          }
        },
        "namespace": {
          "type": "string"
        },
        "params": {
          "type": "array",
          "items": {}
        },
        "phone": {
          "type": "string"
        },
        "useMMlite": {
          "type": "boolean",
          "description": "Force Marketing Messages API (POST marketing_messages).\nIf omitted: auto for MARKETING category when channel has mm_lite_enabled\nand mm_lite_available service settings.\n"
        },
        "messageActivitySharing": {
          "type": "boolean",
          "description": "Sets message_activity_sharing on WABA payload. Enables click tracking webhooks.\nRequires MM Lite path. Ignored on Cloud API fallback.\n"
        },
        "messageSendTtlSeconds": {
          "type": "integer",
          "description": "Template message TTL in seconds (message_send_ttl_seconds).\nMARKETING via MM Lite: 43200–2592000. AUTHENTICATION: 30–900.\nUTILITY: 30–43200. AUTH/UTILITY also accept -1 (30-day custom TTL).\n"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "template",
      "language",
      "namespace",
      "params",
      "phone",
      "useMMlite",
      "messageActivitySharing",
      "messageSendTtlSeconds"
    ]
  },
  {
    "name": "set_conversational_automation",
    "operationId": "setConversationalAutomation",
    "description": "Set conversational automation settings",
    "inputSchema": {
      "type": "object",
      "properties": {
        "enable_welcome_message": {
          "type": "boolean",
          "description": "Enable the automatic welcome message for new conversations"
        },
        "prompts": {
          "type": "array",
          "maxItems": 4,
          "description": "Ice-breaker prompt strings (max 4, each ≤ 80 characters)",
          "items": {
            "type": "string",
            "maxLength": 80
          }
        },
        "commands": {
          "type": "array",
          "maxItems": 30,
          "description": "Slash commands shown in WhatsApp",
          "items": {
            "type": "object",
            "required": [
              "command_name",
              "command_description"
            ],
            "properties": {
              "command_name": {
                "type": "string",
                "maxLength": 32
              },
              "command_description": {
                "type": "string",
                "maxLength": 256
              }
            },
            "additionalProperties": true
          }
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "enable_welcome_message",
      "prompts",
      "commands"
    ]
  },
  {
    "name": "set_webhook",
    "operationId": "setWebhook",
    "description": "Set webhook URL",
    "inputSchema": {
      "type": "object",
      "properties": {
        "webhookUrl": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "webhookUrl"
    ]
  },
  {
    "name": "set_whatsapp_business_encryption",
    "operationId": "setWhatsappBusinessEncryption",
    "description": "Set business encryption public key",
    "inputSchema": {
      "type": "object",
      "properties": {
        "business_public_key": {
          "type": "string",
          "description": "2048-bit RSA public key in PEM format",
          "example": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA...\n-----END PUBLIC KEY-----\n"
        }
      },
      "additionalProperties": false,
      "required": [
        "business_public_key"
      ]
    },
    "inputFields": [
      "business_public_key"
    ]
  },
  {
    "name": "unblock_user",
    "operationId": "unblockUser",
    "description": "Unblock WhatsApp user",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "phone"
      ]
    },
    "inputFields": [
      "phone"
    ]
  },
  {
    "name": "update_calling_settings",
    "operationId": "updateCallingSettings",
    "description": "Update calling settings",
    "inputSchema": {
      "type": "object",
      "properties": {
        "payload": {
          "type": "object",
          "additionalProperties": true,
          "description": "Request body payload"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "payload"
    ]
  },
  {
    "name": "update_me",
    "operationId": "updateMe",
    "description": "Update profile info",
    "inputSchema": {
      "type": "object",
      "properties": {
        "about": {
          "type": "string",
          "description": "Profile About section"
        },
        "address": {
          "type": "string"
        },
        "description": {
          "type": "string",
          "description": "Business description (max 256 characters)"
        },
        "email": {
          "type": "string"
        },
        "vertical": {
          "type": "string",
          "description": "Industry of the business"
        },
        "photo": {
          "type": "string",
          "description": "HTTPS URL or data:image/...;base64,... payload"
        },
        "websites": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "about",
      "address",
      "description",
      "email",
      "vertical",
      "photo",
      "websites"
    ]
  }
];

export const GENERATED_MCP_TOOL_COUNT = GENERATED_MCP_TOOLS.length;
