/* eslint-disable */
/* auto-generated by gen/generate-mcp-tools.js — do not edit */

export interface JsonSchema {
  type?: string | string[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  description?: string;
  additionalProperties?: boolean | JsonSchema;
  enum?: unknown[];
  oneOf?: JsonSchema[];
  format?: string;
  minimum?: number;
  maximum?: number;
  minLength?: number;
  maxLength?: number;
  pattern?: string;
  [key: string]: unknown;
}

export interface GeneratedMcpTool {
  /** MCP tool name (snake_case) */
  name: string;
  /** OpenAPI operationId */
  operationId: string;
  description: string;
  inputSchema: JsonSchema;
  inputFields: string[];
}

export const GENERATED_MCP_TOOLS: GeneratedMcpTool[] = [
  {
    "name": "add_template",
    "operationId": "addTemplate",
    "description": "Create message template",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "category": {
          "type": "string"
        },
        "language": {
          "type": "string"
        },
        "components": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true
          }
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "name",
      "category",
      "language",
      "components"
    ]
  },
  {
    "name": "block_user",
    "operationId": "blockUser",
    "description": "Block WhatsApp user",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "phone"
      ]
    },
    "inputFields": [
      "phone"
    ]
  },
  {
    "name": "create_commerce",
    "operationId": "createCommerce",
    "description": "Update catalog/cart commerce settings via the `params` object.\n\n- `params.is_catalog_visible` — show catalog storefront icon (`true`) or hide it (`false`).\n- `params.is_cart_enabled` — enable cart (`true`) or disable it (`false`).\n\nBlocked when the channel subscription limit is exceeded.\nRequires a commerce-capable channel (Cloud Functions `/commerceWAV2`).\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "params": {
          "type": "object",
          "required": [
            "is_cart_enabled",
            "is_catalog_visible"
          ],
          "properties": {
            "is_cart_enabled": {
              "type": "boolean",
              "description": "Enable cart"
            },
            "is_catalog_visible": {
              "type": "boolean",
              "description": "Show catalog storefront icon"
            }
          },
          "additionalProperties": true
        }
      },
      "additionalProperties": false,
      "required": [
        "params"
      ]
    },
    "inputFields": [
      "params"
    ]
  },
  {
    "name": "create_flows",
    "operationId": "createFlows",
    "description": "Create a WhatsApp Flow (`name` + `categories` required).\nCurrently returns HTTP 501 until the Meta Graph Flows rewrite is available.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "wabaAccountId": {
          "type": "string"
        },
        "name": {
          "type": "string",
          "description": "Flow name"
        },
        "categories": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "SIGN_UP",
              "SIGN_IN",
              "APPOINTMENT_BOOKING",
              "LEAD_GENERATION",
              "CONTACT_US",
              "CUSTOMER_SUPPORT",
              "SURVEY",
              "OTHER"
            ]
          },
          "description": "One or more Flow categories"
        },
        "endpointUri": {
          "type": "string",
          "description": "HTTPS endpoint for the Flow data channel"
        },
        "publish": {
          "type": "boolean",
          "description": "Publish immediately after create"
        },
        "flowJson": {
          "type": "object",
          "additionalProperties": true,
          "description": "Optional Flow JSON document"
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "categories"
      ]
    },
    "inputFields": [
      "wabaAccountId",
      "name",
      "categories",
      "endpointUri",
      "publish",
      "flowJson"
    ]
  },
  {
    "name": "create_flows_flow_id_deprecate",
    "operationId": "createFlowsFlowIdDeprecate",
    "description": "Deprecate Flow",
    "inputSchema": {
      "type": "object",
      "properties": {
        "flowId": {
          "type": "string",
          "description": "Flow ID"
        },
        "wabaAccountId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "flowId"
      ]
    },
    "inputFields": [
      "flowId",
      "wabaAccountId"
    ]
  },
  {
    "name": "create_flows_flow_id_publish",
    "operationId": "createFlowsFlowIdPublish",
    "description": "Publish Flow",
    "inputSchema": {
      "type": "object",
      "properties": {
        "flowId": {
          "type": "string",
          "description": "Flow ID"
        },
        "wabaAccountId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "flowId"
      ]
    },
    "inputFields": [
      "flowId",
      "wabaAccountId"
    ]
  },
  {
    "name": "create_groups",
    "operationId": "createGroups",
    "description": "Create Group",
    "inputSchema": {
      "type": "object",
      "properties": {
        "groupName": {
          "type": "string",
          "description": "Group subject / name"
        },
        "description": {
          "type": "string",
          "description": "Optional group description"
        }
      },
      "additionalProperties": false,
      "required": [
        "groupName"
      ]
    },
    "inputFields": [
      "groupName",
      "description"
    ]
  },
  {
    "name": "create_groups_group_id",
    "operationId": "createGroupsGroupId",
    "description": "Update group subject, description, and/or profile picture.\nPath `groupId` is the WABA group id (without `@g.us`).\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "groupId": {
          "type": "string"
        },
        "subject": {
          "type": "string",
          "description": "New group subject / name"
        },
        "description": {
          "type": "string",
          "description": "New group description"
        },
        "profile_picture_file": {
          "type": "string",
          "description": "Image URL or base64 data URI for the group profile picture"
        }
      },
      "additionalProperties": false,
      "required": [
        "groupId"
      ]
    },
    "inputFields": [
      "groupId",
      "subject",
      "description",
      "profile_picture_file"
    ]
  },
  {
    "name": "create_groups_group_id_invitelink",
    "operationId": "createGroupsGroupIdInvitelink",
    "description": "Reset Invite Link",
    "inputSchema": {
      "type": "object",
      "properties": {
        "groupId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "groupId"
      ]
    },
    "inputFields": [
      "groupId"
    ]
  },
  {
    "name": "create_read_message",
    "operationId": "createReadMessage",
    "description": "Mark message as read",
    "inputSchema": {
      "type": "object",
      "properties": {
        "messageId": {
          "type": "string"
        },
        "msgId": {
          "type": "string"
        },
        "typingIndicator": {
          "type": "boolean",
          "default": false,
          "description": "Show WhatsApp typing indicator (max 25s or until reply)"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "messageId",
      "msgId",
      "typingIndicator"
    ]
  },
  {
    "name": "create_settings",
    "operationId": "createSettings",
    "description": "Update channel settings. Only send fields you want to change.\n\n`webhookUrl` **replaces** the stored list (one URL string, or up to 5 URLs as an array).\nPassing an empty value clears webhooks.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "webhookUrl": {
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          ],
          "description": "Replacement webhook URL, or array of URLs (max 5)"
        },
        "guaranteedHooks": {
          "type": "boolean"
        },
        "ackNotificationsOn": {
          "type": "boolean"
        },
        "rawHooks": {
          "type": "boolean"
        },
        "template_analytics_enabled": {
          "type": "boolean"
        },
        "cta_url_link_tracking_opted_out": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "webhookUrl",
      "guaranteedHooks",
      "ackNotificationsOn",
      "rawHooks",
      "template_analytics_enabled",
      "cta_url_link_tracking_opted_out"
    ]
  },
  {
    "name": "create_upload_media",
    "operationId": "createUploadMedia",
    "description": "Upload a file to WhatsApp media storage and get a numeric `mediaId`\nfor later use with `send_file` / `send_sticker` (`mediaId` field, not `body`).\n\nPass the file as `body` **or** `url` — an HTTP(S) URL or a base64 data URI.\nThe `mediaId` in the response is a numeric string (keep it as a string).\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "body": {
          "type": "string",
          "description": "File HTTP(S) URL or base64 data URI (`data:<mime>;base64,...`)"
        },
        "url": {
          "type": "string",
          "description": "Alias for `body` — public HTTP(S) URL of the file to upload"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "body",
      "url"
    ]
  },
  {
    "name": "delete_flows_flow_id",
    "operationId": "deleteFlowsFlowId",
    "description": "Delete Flow",
    "inputSchema": {
      "type": "object",
      "properties": {
        "flowId": {
          "type": "string",
          "description": "Flow ID"
        },
        "wabaAccountId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "flowId"
      ]
    },
    "inputFields": [
      "flowId",
      "wabaAccountId"
    ]
  },
  {
    "name": "delete_groups_group_id",
    "operationId": "deleteGroupsGroupId",
    "description": "Delete Group",
    "inputSchema": {
      "type": "object",
      "properties": {
        "groupId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "groupId"
      ]
    },
    "inputFields": [
      "groupId"
    ]
  },
  {
    "name": "delete_media",
    "operationId": "deleteMedia",
    "description": "Delete previously uploaded media by numeric `mediaId` (from `/uploadMedia`).\n\nThis is the canonical deletion endpoint and uses the REST `DELETE` verb on the\nmedia resource path. The older `POST /deleteMedia` is a deprecated alias.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "mediaId": {
          "type": "string",
          "description": "Numeric WABA media id"
        }
      },
      "additionalProperties": false,
      "required": [
        "mediaId"
      ]
    },
    "inputFields": [
      "mediaId"
    ]
  },
  {
    "name": "delete_media_legacy",
    "operationId": "deleteMediaLegacy",
    "description": "**Deprecated.** Use `DELETE /media/{mediaId}` instead.\n\nThis POST alias is kept for backward compatibility with earlier integrations.\nNew integrations should call `DELETE /media/{mediaId}`: 1msg follows REST\nconventions for resource deletion going forward (delete a resource with the\n`DELETE` verb on its resource path).\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "mediaId": {
          "type": "string",
          "description": "Numeric WABA media id"
        }
      },
      "additionalProperties": false,
      "required": [
        "mediaId"
      ]
    },
    "inputFields": [
      "mediaId"
    ]
  },
  {
    "name": "get_calling_settings",
    "operationId": "getCallingSettings",
    "description": "Return WhatsApp Calling API settings for this channel (beta).\n\nProxies upstream `GET /calling/settings`.\n\n**Prerequisites**\n- Number must be eligible for Meta Calling (Cloud API; not COEX)\n- Trial / `subscriptionBlocked` channels receive **403** plain text\n- You need your own WebRTC or SIP stack; 1msg is a **signaling proxy** only\n  and does **not** store call history or recordings\n\nSee the **Calling** tag overview for inbound/outbound flows and webhooks.\n",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "get_commerce",
    "operationId": "getCommerce",
    "description": "Returns catalog/cart commerce settings for the channel.\n\nFails with a provider error when the WABA has no catalog linked — that is an\nAPI/account limitation, not an MCP schema bug.\n\n- `is_catalog_visible` — show catalog storefront icon (`true`) or hide it (`false`).\n- `is_cart_enabled` — enable cart (`true`) or disable it (`false`).\n",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "get_conversational_automation",
    "operationId": "getConversationalAutomation",
    "description": "Get WhatsApp conversational components for the channel (welcome message,\nice-breaker prompts, and slash commands).\n\nProxies Meta/360dialog `GET /conversational_automation`.\n\nWhen `enable_welcome_message` is true and a user opens chat for the first\ntime, Meta delivers a webhook message with `type: request_welcome`. The\ninbound formatter exposes that as `type: \"request_welcome\"` and\n`meta.request_welcome: true` so your webhook can send a custom welcome reply.\n",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "get_flows_flow_id",
    "operationId": "getFlowsFlowId",
    "description": "Get Flow Details",
    "inputSchema": {
      "type": "object",
      "properties": {
        "flowId": {
          "type": "string",
          "description": "Flow ID"
        },
        "wabaAccountId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "flowId"
      ]
    },
    "inputFields": [
      "flowId",
      "wabaAccountId"
    ]
  },
  {
    "name": "get_flows_flow_id_preview",
    "operationId": "getFlowsFlowIdPreview",
    "description": "Preview Flow",
    "inputSchema": {
      "type": "object",
      "properties": {
        "flowId": {
          "type": "string",
          "description": "Flow ID"
        },
        "wabaAccountId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "flowId"
      ]
    },
    "inputFields": [
      "flowId",
      "wabaAccountId"
    ]
  },
  {
    "name": "get_groups_group_id",
    "operationId": "getGroupsGroupId",
    "description": "Get Group Info",
    "inputSchema": {
      "type": "object",
      "properties": {
        "groupId": {
          "type": "string"
        },
        "fields": {
          "type": "string",
          "description": "Comma-separated group fields to return"
        }
      },
      "additionalProperties": false,
      "required": [
        "groupId"
      ]
    },
    "inputFields": [
      "groupId",
      "fields"
    ]
  },
  {
    "name": "get_groups_group_id_invitelink",
    "operationId": "getGroupsGroupIdInvitelink",
    "description": "Get Invite Link",
    "inputSchema": {
      "type": "object",
      "properties": {
        "groupId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "groupId"
      ]
    },
    "inputFields": [
      "groupId"
    ]
  },
  {
    "name": "get_me",
    "operationId": "getMe",
    "description": "Get WhatsApp Business Account profile information",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "get_mm_lite_status",
    "operationId": "getMmLiteStatus",
    "description": "Get MM Lite availability and status",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "get_status",
    "operationId": "getStatus",
    "description": "Returns WhatsApp Business API client connection status.",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "get_webhook",
    "operationId": "getWebhook",
    "description": "Returns the configured client webhook URL for this channel.",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "get_whatsapp_business_encryption",
    "operationId": "getWhatsappBusinessEncryption",
    "description": "Retrieve the WhatsApp business public key and signature status for this channel's\nphone number. Required before publishing or sending Flows that use data encryption.\n",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "initiate_call",
    "operationId": "initiateCall",
    "description": "Perform a WhatsApp Calling action (beta).\n\nProxies upstream `POST /calling/calls`. Despite the historical path\nname `/initiateCall`, this endpoint handles **all** call actions:\n\n| action | Use | Required |\n|--------|-----|----------|\n| `connect` | Outbound business → user | `to` + `session` (`sdp_type: offer`) |\n| `pre_accept` | Inbound (optional, reduces audio clipping) | `call_id` + `session` (`sdp_type: answer`) |\n| `accept` | Inbound answer | `call_id` + `session` (`sdp_type: answer`) |\n| `reject` | Decline inbound | `call_id` |\n| `terminate` | Hang up | `call_id` |\n\n**SDP / media (critical)**\n- `accept` / `pre_accept` require a **WebRTC-generated SDP answer**.\n- Do **not** send Meta's offer SDP back as the answer.\n- Postman (or curl) alone **cannot** establish real media — you need a\n  WebRTC or SIP stack. 1msg only proxies signaling.\n\nAnswer within ~**30–60 seconds** of an inbound `connect` webhook or Meta\nterminates as unanswered. Common Meta errors include Calling not enabled\n(`138000`), no permission (`138006`), SDP validation failures.\n\n**Outbound** requires a prior Call Permission Request (CPR) acceptance.\nSee the **Calling** tag overview for the full outbound flow and CPR limits.\n\nTrial / `subscriptionBlocked` → **403** plain text.\nUpstream failures often return HTTP 200 with `{ \"response\": { \"error\": \"...\" } }`.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "messaging_product": {
          "type": "string",
          "description": "Must be `whatsapp`",
          "enum": [
            "whatsapp"
          ],
          "example": "whatsapp"
        },
        "action": {
          "type": "string",
          "description": "Call control action",
          "enum": [
            "connect",
            "pre_accept",
            "accept",
            "reject",
            "terminate"
          ],
          "example": "connect"
        },
        "call_id": {
          "type": "string",
          "description": "WhatsApp call id from the inbound/outbound calls webhook (`calls[].id`).\nRequired for `pre_accept`, `accept`, `reject`, `terminate`.\n",
          "example": "wacid.ABGGFjFVU2AfAgo6V-Hc5eCgK5Gh"
        },
        "to": {
          "type": "string",
          "description": "Recipient WhatsApp user phone (digits, country code, no +).\nRequired for outbound `connect`.\n",
          "example": "12185552828"
        },
        "biz_opaque_callback_data": {
          "type": "string",
          "description": "Optional opaque string echoed on later call webhooks for correlation",
          "maxLength": 512,
          "example": "order-123-callback"
        },
        "session": {
          "type": "object",
          "description": "WebRTC SDP session (required for connect / pre_accept / accept)",
          "required": [
            "sdp_type",
            "sdp"
          ],
          "properties": {
            "sdp_type": {
              "type": "string",
              "description": "offer for outbound connect; answer for pre_accept/accept",
              "enum": [
                "offer",
                "answer"
              ],
              "example": "offer"
            },
            "sdp": {
              "type": "string",
              "description": "Full SDP (RFC 8866). Replace placeholders with SDP from your WebRTC stack.\nMust negotiate ICE, DTLS-SRTP, and OPUS for WhatsApp media.\n",
              "example": "[REPLACE_WITH_WEBRTC_SDP]"
            }
          },
          "additionalProperties": true
        }
      },
      "additionalProperties": false,
      "required": [
        "messaging_product",
        "action"
      ]
    },
    "inputFields": [
      "messaging_product",
      "action",
      "call_id",
      "to",
      "biz_opaque_callback_data",
      "session"
    ]
  },
  {
    "name": "list_blocked_users",
    "operationId": "listBlockedUsers",
    "description": "Returns users currently blocked on this WhatsApp channel (WABA `GET /block_users`).\nSame channel token auth as `blockUser` / `unblockUser`.\n",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "list_flows",
    "operationId": "listFlows",
    "description": "List WhatsApp Flows for the WABA.\nCurrently returns HTTP 501 until the Meta Graph Flows rewrite is available.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "wabaAccountId": {
          "type": "string"
        },
        "fields": {
          "type": "string",
          "description": "Comma-separated Flow fields to return"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "wabaAccountId",
      "fields"
    ]
  },
  {
    "name": "list_groups",
    "operationId": "listGroups",
    "description": "List WhatsApp groups for this channel. Paginate with `limit`, `before`, and `after`.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "limit": {
          "type": "integer",
          "description": "Max groups to return"
        },
        "before": {
          "type": "string",
          "description": "Cursor for the previous page"
        },
        "after": {
          "type": "string",
          "description": "Cursor for the next page"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "limit",
      "before",
      "after"
    ]
  },
  {
    "name": "list_messages",
    "operationId": "listMessages",
    "description": "List stored chat history for this channel (requires history storage).\nFilter with `chatId`, `limit`, `last`, message numbers, or time bounds.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "chatId": {
          "type": "string",
          "description": "Filter messages for one chat (`phone@c.us`, group `@g.us`, or BSUID `@lid`)"
        },
        "limit": {
          "type": "integer",
          "description": "Max rows to return (default 100)"
        },
        "last": {
          "type": "boolean",
          "description": "If true, return the latest messages (DESC). Default false."
        },
        "lastMessageNumber": {
          "type": "integer"
        },
        "firstMessageNumber": {
          "type": "integer"
        },
        "min_time": {
          "type": "integer",
          "description": "Unix timestamp lower bound"
        },
        "max_time": {
          "type": "integer",
          "description": "Unix timestamp upper bound"
        },
        "msgId": {
          "type": "string",
          "description": "Filter by stored message id"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "chatId",
      "limit",
      "last",
      "lastMessageNumber",
      "firstMessageNumber",
      "min_time",
      "max_time",
      "msgId"
    ]
  },
  {
    "name": "list_settings",
    "operationId": "listSettings",
    "description": "Return channel settings: webhook URL(s), delivery flags, and analytics toggles.\n\nThis is the same `GET /settings` endpoint as the REST API (previously missing from MCP).\n",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "inputFields": []
  },
  {
    "name": "list_templates",
    "operationId": "listTemplates",
    "description": "List message templates. Paginate with `limit` / `offset`; sort by `id`, `name`, or `status`.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "limit": {
          "type": "integer"
        },
        "offset": {
          "type": "integer"
        },
        "sort": {
          "type": "string",
          "enum": [
            "id",
            "name",
            "status"
          ],
          "description": "Sort field (`id`, `name`, or `status`)"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "limit",
      "offset",
      "sort"
    ]
  },
  {
    "name": "patch_flows_flow_id_assets",
    "operationId": "patchFlowsFlowIdAssets",
    "description": "Replace the Flow JSON document (`flowJson`).\nCurrently returns HTTP 501 until the Meta Graph Flows rewrite is available.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "flowId": {
          "type": "string",
          "description": "Flow ID"
        },
        "wabaAccountId": {
          "type": "string"
        },
        "flowJson": {
          "type": "object",
          "additionalProperties": true,
          "description": "WhatsApp Flow JSON document"
        }
      },
      "additionalProperties": false,
      "required": [
        "flowId",
        "flowJson"
      ]
    },
    "inputFields": [
      "flowId",
      "wabaAccountId",
      "flowJson"
    ]
  },
  {
    "name": "patch_flows_flow_id_metadata",
    "operationId": "patchFlowsFlowIdMetadata",
    "description": "Update Flow `name`, `categories`, and/or `endpointUri`.\nCurrently returns HTTP 501 until the Meta Graph Flows rewrite is available.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "flowId": {
          "type": "string",
          "description": "Flow ID"
        },
        "wabaAccountId": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "categories": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "SIGN_UP",
              "SIGN_IN",
              "APPOINTMENT_BOOKING",
              "LEAD_GENERATION",
              "CONTACT_US",
              "CUSTOMER_SUPPORT",
              "SURVEY",
              "OTHER"
            ]
          }
        },
        "endpointUri": {
          "type": "string",
          "description": "HTTPS endpoint for the Flow data channel"
        }
      },
      "additionalProperties": false,
      "required": [
        "flowId"
      ]
    },
    "inputFields": [
      "flowId",
      "wabaAccountId",
      "name",
      "categories",
      "endpointUri"
    ]
  },
  {
    "name": "remove_template",
    "operationId": "removeTemplate",
    "description": "Delete a message template by `name` (all language versions of that name).",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Template name to delete"
        }
      },
      "additionalProperties": false,
      "required": [
        "name"
      ]
    },
    "inputFields": [
      "name"
    ]
  },
  {
    "name": "retrieve_media",
    "operationId": "retrieveMedia",
    "description": "Get WABA media URL and metadata by mediaId (from uploadMedia).\nThe returned `url` is temporary and typically expires within ~5 minutes.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "mediaId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "mediaId"
      ]
    },
    "inputFields": [
      "mediaId"
    ]
  },
  {
    "name": "send_address_message",
    "operationId": "sendAddressMessage",
    "description": "Request shipping address from the user (WhatsApp interactive `address_message`).\n\n**India and Singapore only.** Requires:\n- Business WhatsApp number registered in that country\n- Recipient phone matching the country (`+91` ↔ `IN`, `+65` ↔ `SG`)\n\nPass `country: \"IN\"` or `country: \"SG\"`. Eligibility is validated upstream;\nmismatches (e.g. Singapore phone with `country: \"IN\"`) return errors such as\n`Unsupported Interactive Message type` (HTTP 200 with `sent: false`).\n\nOptional action parameters: `values`, `saved_addresses`, `validation_errors`.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "integer",
          "description": "Recipient phone (E.164 digits, no +). Must match country."
        },
        "chatId": {
          "type": "string"
        },
        "body": {
          "type": "string",
          "description": "Body text shown with the address request"
        },
        "country": {
          "type": "string",
          "enum": [
            "IN",
            "SG"
          ],
          "description": "Address form country. Defaults to IN if omitted.",
          "example": "SG"
        },
        "values": {
          "type": "object",
          "description": "Optional prefilled address fields",
          "additionalProperties": true
        },
        "saved_addresses": {
          "type": "array",
          "description": "Optional previously saved addresses for the user",
          "items": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "validation_errors": {
          "type": "object",
          "description": "Optional field validation errors when re-prompting",
          "additionalProperties": true
        },
        "quotedMsgId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "body"
      ]
    },
    "inputFields": [
      "phone",
      "chatId",
      "body",
      "country",
      "values",
      "saved_addresses",
      "validation_errors",
      "quotedMsgId"
    ]
  },
  {
    "name": "send_button",
    "operationId": "sendButton",
    "description": "Send Reply Buttons Message",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "string",
          "description": "Recipient phone with country code. Use phone or chatId."
        },
        "chatId": {
          "type": "string",
          "description": "Recipient chat ID (`phone@c.us`, group `@g.us`, or BSUID `@lid`). Use phone or chatId."
        },
        "quotedMsgId": {
          "type": "string",
          "description": "Optional Cloud API wamid to quote"
        },
        "body": {
          "type": "string"
        },
        "footer": {
          "type": "string"
        },
        "header": {
          "type": "object",
          "additionalProperties": true,
          "description": "Optional interactive header (text/image/video/document)"
        },
        "buttons": {
          "type": "array",
          "items": {
            "type": "object"
          },
          "description": "Legacy alias for sections (`[{id,title}]`)"
        },
        "sections": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "reply": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string",
                    "format": "utc-millisec"
                  },
                  "title": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "phone",
      "chatId",
      "quotedMsgId",
      "body",
      "footer",
      "header",
      "buttons",
      "sections"
    ]
  },
  {
    "name": "send_carousel",
    "operationId": "sendCarousel",
    "description": "You can send product cards via Carousel in two ways:\n\nTemplate messages: do not require a 24-hour customer service window between you and the recipient. Use sendTemplate.\n\nFree-form messages: can be sent only when a customer service window is open between you and the recipient. Use sendCarousel.\n\nThe message structure in /sendCarousel is largely similar to sending a template. However, in this case you must \nexplicitly specify all elements that are created in advance when working with templates. This is because the message \nis sent without using a template.\n\nIn /sendCarousel, for a Catalog Carousel there can be either 1 URL button or one or more quick reply buttons.\n\nPrefer the simple `cards` array (2–10 cards). Each card needs a header media/product\nplus a CTA URL or quick-reply buttons. Example:\n\n```json\n{\n  \"phone\": \"79001234567\",\n  \"body\": \"Pick a product\",\n  \"cards\": [\n    {\n      \"header\": { \"type\": \"image\", \"image\": { \"link\": \"https://example.com/1.jpg\" } },\n      \"body\": { \"text\": \"Card one\" },\n      \"type\": \"cta_url\",\n      \"action\": { \"name\": \"cta_url\", \"parameters\": { \"url\": \"https://example.com/p1\", \"display_text\": \"Open\" } }\n    },\n    {\n      \"header\": { \"type\": \"image\", \"image\": { \"link\": \"https://example.com/2.jpg\" } },\n      \"body\": { \"text\": \"Card two\" },\n      \"type\": \"cta_url\",\n      \"action\": { \"name\": \"cta_url\", \"parameters\": { \"url\": \"https://example.com/p2\", \"display_text\": \"Open\" } }\n    }\n  ]\n}\n```\n\n`params` with a `CAROUSEL` component is the template-like alternative.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "body": {
          "type": "string",
          "description": "Text shown above the carousel"
        },
        "cards": {
          "type": "array",
          "minItems": 2,
          "maxItems": 10,
          "description": "Preferred. 2–10 carousel cards.",
          "items": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "params": {
          "type": "array",
          "items": {
            "type": "object"
          },
          "description": "Template-like alternative — include a CAROUSEL component with cards"
        },
        "quotedMsgId": {
          "type": "string",
          "description": "Quoted message ID (Cloud API)"
        },
        "chatId": {
          "type": "string",
          "description": "Required if phone is not set. Chat ID from the message list. Examples: 12020721369@c.us or 120363046942338209@g.us(group)"
        },
        "phone": {
          "type": "integer",
          "description": "Required if chatId is not set. A phone number starting with the country code. USA example: 12020721369."
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "body",
      "cards",
      "params",
      "quotedMsgId",
      "chatId",
      "phone"
    ]
  },
  {
    "name": "send_contact",
    "operationId": "sendContact",
    "description": "Send a WhatsApp contact card.\n\nPreferred simple body (legacy-compatible):\n\n```json\n{\n  \"phone\": \"79001234567\",\n  \"contact\": { \"name\": \"Lida\", \"phone\": \"+79181976551\" }\n}\n```\n\nCloud API shape also works: `contacts` is an array of objects with\n`name.formatted_name` and `phones[].phone` (E.164 string, **not** a timestamp).\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "string",
          "description": "Recipient phone with country code. Use phone or chatId."
        },
        "chatId": {
          "type": "string",
          "description": "Recipient chat ID (`phone@c.us`, group `@g.us`, or BSUID `@lid`). Use phone or chatId."
        },
        "quotedMsgId": {
          "type": "string"
        },
        "contact": {
          "type": "object",
          "description": "Simple contact card. Use this or `contacts`.",
          "required": [
            "name",
            "phone"
          ],
          "properties": {
            "name": {
              "description": "Display name (string) or Cloud API name object",
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "type": "object",
                  "additionalProperties": true
                }
              ]
            },
            "phone": {
              "type": "string",
              "description": "Contact phone in E.164 (`+79181976551`), not a timestamp"
            },
            "email": {
              "type": "string"
            },
            "org": {
              "type": "object",
              "additionalProperties": true
            },
            "url": {
              "type": "string"
            }
          }
        },
        "contacts": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "object",
                "properties": {
                  "formatted_name": {
                    "type": "string"
                  },
                  "first_name": {
                    "type": "string"
                  },
                  "last_name": {
                    "type": "string"
                  },
                  "middle_name": {
                    "type": "string"
                  },
                  "suffix": {
                    "type": "string"
                  },
                  "prefix": {
                    "type": "string"
                  }
                }
              },
              "birthday": {
                "type": "string"
              },
              "addresses": {
                "type": "array",
                "items": {
                  "type": "object",
                  "additionalProperties": true
                }
              },
              "emails": {
                "type": "array",
                "items": {
                  "type": "object",
                  "additionalProperties": true
                }
              },
              "org": {
                "type": "object",
                "properties": {
                  "company": {
                    "type": "string"
                  },
                  "department": {
                    "type": "string"
                  },
                  "title": {
                    "type": "string"
                  }
                }
              },
              "phones": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "phone": {
                      "type": "string",
                      "description": "E.164 phone (`+79181976551`). Not a timestamp."
                    },
                    "type": {
                      "type": "string"
                    },
                    "wa_id": {
                      "type": "string"
                    }
                  }
                }
              },
              "urls": {
                "type": "array",
                "items": {
                  "type": "object",
                  "additionalProperties": true
                }
              }
            }
          }
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "phone",
      "chatId",
      "quotedMsgId",
      "contact",
      "contacts"
    ]
  },
  {
    "name": "send_cta_url",
    "operationId": "sendCtaUrl",
    "description": "Send an interactive message with a single call-to-action URL button.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "integer"
        },
        "chatId": {
          "type": "string"
        },
        "body": {
          "type": "string"
        },
        "displayText": {
          "type": "string",
          "description": "Button label"
        },
        "url": {
          "type": "string",
          "format": "uri"
        },
        "header": {
          "type": "object",
          "additionalProperties": true
        },
        "footer": {
          "type": "string"
        },
        "quotedMsgId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "body",
        "displayText",
        "url"
      ]
    },
    "inputFields": [
      "phone",
      "chatId",
      "body",
      "displayText",
      "url",
      "header",
      "footer",
      "quotedMsgId"
    ]
  },
  {
    "name": "send_file",
    "operationId": "sendFile",
    "description": "Send a file to an existing chat. (Only if the dialogue has an Open Session). \nOnly one of two parameters is needed to determine the destination - chatId or phone.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "body": {
          "type": "string",
          "description": "File source (required unless mediaId is set):\n- HTTP/HTTPS URL\n- Base64 data URI\n"
        },
        "filename": {
          "type": "string",
          "description": "File name with extension (required with body, not with mediaId)"
        },
        "mediaId": {
          "type": "string",
          "description": "WABA media id from uploadMedia (alternative to body)"
        },
        "mediaType": {
          "type": "string",
          "enum": [
            "image",
            "video",
            "audio",
            "document"
          ],
          "description": "Required when using mediaId"
        },
        "voice": {
          "type": "boolean",
          "description": "Native WhatsApp voice note (audio/ogg only)"
        },
        "caption": {
          "type": "string",
          "maxLength": 1024
        },
        "quotedMsgId": {
          "type": "string"
        },
        "chatId": {
          "type": "string"
        },
        "phone": {
          "type": "integer"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "body",
      "filename",
      "mediaId",
      "mediaType",
      "voice",
      "caption",
      "quotedMsgId",
      "chatId",
      "phone"
    ]
  },
  {
    "name": "send_flow",
    "operationId": "sendFlow",
    "description": "Send Interactive WhatsApp Flow message to an existing chat. (Only if the dialogue has an Open Session). \nOnly one of two parameters is needed to determine the destination - chatId or phone.\n\nUse this method to send a published WhatsApp Flow as a service (interactive) message. \nIf the 24-hour window is closed, send a template with a FLOW button via /sendTemplate.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "body": {
          "type": "string",
          "description": "Flow message body text"
        },
        "header": {
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "object"
            }
          ],
          "description": "Flow header (string or text header object)"
        },
        "footer": {
          "type": "string",
          "description": "Footer text"
        },
        "flowId": {
          "type": "string",
          "description": "Published Flow ID"
        },
        "flowToken": {
          "type": "string",
          "description": "Flow token generated by the business"
        },
        "flowCta": {
          "type": "string",
          "description": "CTA button text"
        },
        "flowAction": {
          "type": "string",
          "enum": [
            "navigate",
            "data_exchange"
          ],
          "description": "Flow action type"
        },
        "flowActionPayload": {
          "type": "object",
          "description": "Required for flowAction=navigate (screen is required). Ignored for data_exchange. If data is provided, it must be a non-empty object."
        },
        "flowMessageVersion": {
          "type": "string",
          "description": "Flow message version (default \"3\")"
        },
        "mode": {
          "type": "string",
          "enum": [
            "draft",
            "published"
          ],
          "description": "Flow mode (draft or published). If omitted, provider default applies"
        },
        "flowActionData": {
          "type": "object",
          "description": "Shortcut for flowActionPayload.data (optional)"
        },
        "flowActionScreen": {
          "type": "string",
          "description": "Shortcut for flowActionPayload.screen (optional)"
        },
        "quotedMsgId": {
          "type": "string",
          "description": "Quoted message ID (Cloud API)"
        },
        "chatId": {
          "type": "string",
          "description": "Required if phone is not set. Chat ID from the message list. Examples: 12020721369@c.us or 120363046942338209@g.us(group)"
        },
        "phone": {
          "type": "integer",
          "description": "Required if chatId is not set. A phone number starting with the country code. USA example: 12020721369."
        }
      },
      "additionalProperties": false,
      "required": [
        "body",
        "flowId",
        "flowToken",
        "flowCta"
      ]
    },
    "inputFields": [
      "body",
      "header",
      "footer",
      "flowId",
      "flowToken",
      "flowCta",
      "flowAction",
      "flowActionPayload",
      "flowMessageVersion",
      "mode",
      "flowActionData",
      "flowActionScreen",
      "quotedMsgId",
      "chatId",
      "phone"
    ]
  },
  {
    "name": "send_list",
    "operationId": "sendList",
    "description": "Send List Message",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "string",
          "description": "Recipient phone with country code. Use phone or chatId."
        },
        "chatId": {
          "type": "string",
          "description": "Recipient chat ID (`phone@c.us`, group `@g.us`, or BSUID `@lid`). Use phone or chatId."
        },
        "quotedMsgId": {
          "type": "string"
        },
        "body": {
          "type": "string"
        },
        "buttonText": {
          "type": "string"
        },
        "action": {
          "type": "string"
        },
        "sections": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "title": {
                "type": "string"
              },
              "rows": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "format": "utc-millisec"
                    },
                    "title": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "phone",
      "chatId",
      "quotedMsgId",
      "body",
      "buttonText",
      "action",
      "sections"
    ]
  },
  {
    "name": "send_location",
    "operationId": "sendLocation",
    "description": "Send a location to an existing chat. (Only if the dialogue has an Open Session). \nOnly one of two parameters is needed to determine the destination - chatId or phone.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "lat": {
          "type": "string",
          "description": "Latitude of the location. Example: 45.018337"
        },
        "lng": {
          "type": "string",
          "description": "Longitude of the location. Example: -73.968285"
        },
        "address": {
          "type": "string",
          "description": "Address of the location. Only displayed if name is present. Example: 9766 Valley View St., New York, NY 10024"
        },
        "name": {
          "type": "string",
          "description": "Name of the location. Example: Facebook HQ"
        },
        "quotedMsgId": {
          "type": "string",
          "description": "Quoted message ID (Cloud API)"
        },
        "chatId": {
          "type": "string",
          "description": "Required if phone is not set. Chat ID from the message list. Examples: 12020721369@c.us or 120363046942338209@g.us(group)"
        },
        "phone": {
          "type": "integer",
          "description": "Required if chatId is not set. A phone number starting with the country code. USA example: 12020721369."
        }
      },
      "additionalProperties": false,
      "required": [
        "lat",
        "lng"
      ]
    },
    "inputFields": [
      "lat",
      "lng",
      "address",
      "name",
      "quotedMsgId",
      "chatId",
      "phone"
    ]
  },
  {
    "name": "send_location_request",
    "operationId": "sendLocationRequest",
    "description": "Send Location Request Message",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "string",
          "description": "Recipient phone with country code. Use phone or chatId."
        },
        "chatId": {
          "type": "string",
          "description": "Recipient chat ID (`phone@c.us`, group `@g.us`, or BSUID `@lid`). Use phone or chatId."
        },
        "quotedMsgId": {
          "type": "string"
        },
        "body": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "phone",
      "chatId",
      "quotedMsgId",
      "body"
    ]
  },
  {
    "name": "send_message",
    "operationId": "sendMessage",
    "description": "Send a message to an existing chat. (Only if the dialogue has an Open Session). \nThe message will be added to the queue for sending and delivered even if the phone \nis disconnected from the Internet or authorization is not passed.\n\nOnly one of two parameters is needed to determine the destination - chatId or phone.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "body": {
          "type": "string",
          "description": "Message text, UTF-8 or UTF-16 string with emoji",
          "minLength": 1,
          "maxLength": 4096,
          "example": "Hello World 🌍"
        },
        "quotedMsgId": {
          "type": "string",
          "description": "Message ID to quote/reply to (Cloud API wamid)",
          "pattern": "^wamid\\..+$",
          "example": "wamid.HBgNMTIwMjA3MjEzNjkVAgARGBI5RTBCNUY0QUE2RjZBQzhGNDkA"
        },
        "chatId": {
          "type": "string",
          "description": "Recipient chat ID: phone@c.us, group@g.us, or BSUID@lid",
          "example": "12020721369@c.us"
        },
        "phone": {
          "type": "integer",
          "description": "Phone number starting with country code (alternative to chatId)",
          "minimum": 1000000000,
          "maximum": 999999999999999,
          "example": 12020721369
        }
      },
      "additionalProperties": false,
      "required": [
        "body"
      ]
    },
    "inputFields": [
      "body",
      "quotedMsgId",
      "chatId",
      "phone"
    ]
  },
  {
    "name": "send_order_details",
    "operationId": "sendOrderDetails",
    "description": "Send a WhatsApp **order details** payment / invoice message using a\npre-approved **Utility** template that has an `ORDER_DETAILS` button.\n\n**India only** (WhatsApp Payments India). Requires:\n- India WhatsApp Business number\n- Commerce enabled on the channel (`GET`/`POST /commerce`)\n- Approved template with an `ORDER_DETAILS` button\n\nUse this method when you need structured fields (`order`, `referenceId`,\n`currency`, `paymentSettings`). The API appends a template button\n`sub_type: order_details` and sends via the same path as `POST /sendTemplate`.\n\nWorks **outside the 24-hour session window** (template message).\n\nYou can also send the same payload yourself with `POST /sendTemplate` by\nincluding a button component in `params`:\n\n```json\n{\n  \"type\": \"button\",\n  \"sub_type\": \"order_details\",\n  \"index\": 0,\n  \"parameters\": [{\n    \"type\": \"action\",\n    \"action\": {\n      \"order_details\": {\n        \"reference_id\": \"order-123\",\n        \"currency\": \"INR\",\n        \"order\": { \"status\": \"pending\", \"items\": [], \"subtotal\": { \"offset\": 100, \"value\": 50000 } }\n      }\n    }\n  }]\n}\n```\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "integer",
          "description": "Recipient phone (India E.164 digits, no +). Use phone or chatId.",
          "example": 919876543210
        },
        "chatId": {
          "type": "string",
          "description": "Recipient chatId (e.g. phone@c.us). Use phone or chatId."
        },
        "template": {
          "type": "string",
          "description": "Approved Utility template name that includes an ORDER_DETAILS button",
          "example": "order_details_utility"
        },
        "namespace": {
          "type": "string",
          "description": "Template namespace from the channel / template list",
          "example": "your_namespace_uuid"
        },
        "language": {
          "type": "object",
          "description": "Template language",
          "required": [
            "code"
          ],
          "properties": {
            "code": {
              "type": "string",
              "description": "Language code",
              "example": "en"
            },
            "policy": {
              "type": "string",
              "description": "Optional language policy",
              "example": "deterministic"
            }
          },
          "additionalProperties": true
        },
        "params": {
          "type": "array",
          "description": "Extra template components (HEADER / BODY / etc.). If an order_details button is missing, the API appends one from order / referenceId / currency / paymentSettings.\n",
          "items": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "referenceId": {
          "type": "string",
          "description": "Unique order / payment reference id (maps to reference_id)",
          "example": "order-123"
        },
        "currency": {
          "type": "string",
          "description": "Currency code for India payments",
          "example": "INR"
        },
        "paymentSettings": {
          "type": "object",
          "description": "Optional payment settings (UPI / payment gateway / payment link). Forwarded as payment_settings on the order_details action.\n",
          "additionalProperties": true
        },
        "order": {
          "type": "object",
          "description": "Order payload for the ORDER_DETAILS button. Typical fields: status, items[], subtotal, tax, shipping, discount. Amount objects use `{ \"offset\": 100, \"value\": <minor_units> }` (e.g. value 50000 with offset 100 = ₹500.00).\n",
          "required": [
            "items"
          ],
          "properties": {
            "status": {
              "type": "string",
              "description": "Order status",
              "example": "pending"
            },
            "items": {
              "type": "array",
              "description": "Line items",
              "items": {
                "type": "object",
                "properties": {
                  "retailer_id": {
                    "type": "string",
                    "example": "SKU-1"
                  },
                  "name": {
                    "type": "string",
                    "example": "Item"
                  },
                  "quantity": {
                    "type": "integer",
                    "example": 1
                  },
                  "amount": {
                    "type": "object",
                    "properties": {
                      "offset": {
                        "type": "integer",
                        "example": 100
                      },
                      "value": {
                        "type": "integer",
                        "example": 50000
                      }
                    },
                    "additionalProperties": true
                  }
                },
                "additionalProperties": true
              }
            },
            "subtotal": {
              "type": "object",
              "properties": {
                "offset": {
                  "type": "integer",
                  "example": 100
                },
                "value": {
                  "type": "integer",
                  "example": 50000
                }
              },
              "additionalProperties": true
            },
            "tax": {
              "type": "object",
              "additionalProperties": true
            },
            "shipping": {
              "type": "object",
              "additionalProperties": true
            },
            "discount": {
              "type": "object",
              "additionalProperties": true
            }
          },
          "additionalProperties": true
        }
      },
      "additionalProperties": false,
      "required": [
        "template",
        "namespace",
        "language",
        "order"
      ]
    },
    "inputFields": [
      "phone",
      "chatId",
      "template",
      "namespace",
      "language",
      "params",
      "referenceId",
      "currency",
      "paymentSettings",
      "order"
    ]
  },
  {
    "name": "send_payment_request",
    "operationId": "sendPaymentRequest",
    "description": "Send a regional payment request interactive message (beta scaffold).\n`region` must be IN, SG, or BR. Payload shape follows Meta regional payments docs;\nverify on stage before production use. Full regional builders are not implemented yet.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "integer"
        },
        "region": {
          "type": "string",
          "enum": [
            "IN",
            "SG",
            "BR"
          ]
        },
        "body": {
          "type": "string"
        },
        "interactive": {
          "type": "object",
          "additionalProperties": true
        },
        "action": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "additionalProperties": false,
      "required": [
        "phone",
        "region"
      ]
    },
    "inputFields": [
      "phone",
      "region",
      "body",
      "interactive",
      "action"
    ]
  },
  {
    "name": "send_product",
    "operationId": "sendProduct",
    "description": "Send a single catalog product or a product list.\nDestination is `chatId` or `phone`. `action` is required:\n- single product: `{ \"catalog_id\": \"...\", \"product_retailer_id\": \"...\" }`\n- product list: `{ \"catalog_id\": \"...\", \"sections\": [{ \"title\": \"...\", \"product_items\": [{ \"product_retailer_id\": \"...\" }] }] }`\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "string",
          "description": "Recipient phone with country code. Use phone or chatId."
        },
        "chatId": {
          "type": "string",
          "description": "Recipient chat ID (`phone@c.us`, group `@g.us`, or BSUID `@lid`). Use phone or chatId."
        },
        "quotedMsgId": {
          "type": "string"
        },
        "body": {
          "type": "string",
          "description": "Optional message text shown with the product"
        },
        "footer": {
          "type": "string"
        },
        "header": {
          "type": "string",
          "description": "Text header (product list only)"
        },
        "action": {
          "type": "object",
          "additionalProperties": true,
          "description": "Catalog action (`catalog_id` + `product_retailer_id`, or `sections` for a list)"
        }
      },
      "additionalProperties": false,
      "required": [
        "action"
      ]
    },
    "inputFields": [
      "phone",
      "chatId",
      "quotedMsgId",
      "body",
      "footer",
      "header",
      "action"
    ]
  },
  {
    "name": "send_reaction",
    "operationId": "sendReaction",
    "description": "Send Reaction",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "string",
          "description": "Recipient phone with country code. Use phone or chatId."
        },
        "chatId": {
          "type": "string",
          "description": "Recipient chat ID (`phone@c.us`, group `@g.us`, or BSUID `@lid`). Use phone or chatId."
        },
        "body": {
          "type": "string"
        },
        "quotedMsgId": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "phone",
      "chatId",
      "body",
      "quotedMsgId"
    ]
  },
  {
    "name": "send_sticker",
    "operationId": "sendSticker",
    "description": "Send a WhatsApp sticker by mediaId or link URL.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "integer"
        },
        "chatId": {
          "type": "string"
        },
        "mediaId": {
          "type": "string",
          "description": "WABA media id from uploadMedia"
        },
        "link": {
          "type": "string",
          "description": "Public URL to webp sticker"
        },
        "quotedMsgId": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "phone",
      "chatId",
      "mediaId",
      "link",
      "quotedMsgId"
    ]
  },
  {
    "name": "send_template",
    "operationId": "sendTemplate",
    "description": "Send a WhatsApp **template** message (works outside the 24-hour session window).\n\nUse this tool — not `send_message` — when the 24h session is closed.\n\n`params` MUST be Cloud API **component objects**, never a flat list of strings\nand never the old On-Prem `hsm` / `localizable_params` format.\n\nExample body variable `{{1}}`:\n\n```json\n{\n  \"type\": \"body\",\n  \"parameters\": [{ \"type\": \"text\", \"text\": \"Ivan\" }]\n}\n```\n\nDo not send `\"type\": \"hsm\"` and do not send `params: [\"Ivan\", \"123\"]`.\n\nSupported `params` button `sub_type` values include: `url`, `quick_reply`,\n`copy_code` / `coupon_code`, `catalog`, `flow`, `limited_time_offer`, and\n**`order_details`** (WhatsApp Payments **India only** — requires an approved\nUtility template with an ORDER_DETAILS button).\n\nConvenience wrapper with structured fields: `POST /sendOrderDetails`.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "template": {
          "type": "string",
          "description": "Approved template name (template `name`, not the old HSM `element_name`)"
        },
        "language": {
          "type": "object",
          "description": "Template language. Always set `policy` to `deterministic`.",
          "properties": {
            "policy": {
              "type": "string",
              "description": "Must be `deterministic`",
              "example": "deterministic",
              "default": "deterministic"
            },
            "code": {
              "type": "string",
              "example": "en"
            }
          }
        },
        "namespace": {
          "type": "string",
          "description": "Template namespace from `list_templates`"
        },
        "params": {
          "type": "array",
          "description": "Template components in WhatsApp Cloud API format.\nEach item is an object with `type` (`body`, `header`, `button`)\nand `parameters` (objects with `type` + `text` / media / action).\nNever a list of strings. Never HSM `localizable_params`.\n",
          "items": {
            "type": "object",
            "additionalProperties": true,
            "description": "Component object, e.g. {\"type\":\"body\",\"parameters\":[{\"type\":\"text\",\"text\":\"Ivan\"}]} or a header/button/carousel component. Not a string.\n"
          }
        },
        "phone": {
          "type": "string",
          "description": "Recipient phone with country code (use phone or chatId)"
        },
        "chatId": {
          "type": "string",
          "description": "Recipient chat ID (`phone@c.us`, group `@g.us`, or BSUID `@lid`). Use phone or chatId."
        },
        "quotedMsgId": {
          "type": "string",
          "description": "Optional Cloud API wamid to quote"
        },
        "useMMlite": {
          "type": "boolean",
          "description": "Force Marketing Messages API (POST marketing_messages).\nIf omitted: auto for MARKETING category when channel has mm_lite_enabled\nand mm_lite_available service settings.\n"
        },
        "messageActivitySharing": {
          "type": "boolean",
          "description": "Sets message_activity_sharing on WABA payload. Enables click tracking webhooks.\nRequires MM Lite path. Ignored on Cloud API fallback.\n"
        },
        "messageSendTtlSeconds": {
          "type": "integer",
          "description": "Template message TTL in seconds (message_send_ttl_seconds).\nMARKETING via MM Lite: 43200–2592000. AUTHENTICATION: 30–900.\nUTILITY: 30–43200. AUTH/UTILITY also accept -1 (30-day custom TTL).\n"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "template",
      "language",
      "namespace",
      "params",
      "phone",
      "chatId",
      "quotedMsgId",
      "useMMlite",
      "messageActivitySharing",
      "messageSendTtlSeconds"
    ]
  },
  {
    "name": "set_conversational_automation",
    "operationId": "setConversationalAutomation",
    "description": "Update WhatsApp conversational components.\n\nAllowed body fields (others are ignored):\n- `enable_welcome_message` (boolean)\n- `prompts` (string[], max 4, each ≤ 80 chars)\n- `commands` (`{ command_name, command_description }[]`)\n\nProxies Meta/360dialog `POST /conversational_automation`.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "enable_welcome_message": {
          "type": "boolean",
          "description": "Enable the automatic welcome message for new conversations"
        },
        "prompts": {
          "type": "array",
          "maxItems": 4,
          "description": "Ice-breaker prompt strings (max 4, each ≤ 80 characters)",
          "items": {
            "type": "string",
            "maxLength": 80
          }
        },
        "commands": {
          "type": "array",
          "maxItems": 30,
          "description": "Slash commands shown in WhatsApp",
          "items": {
            "type": "object",
            "required": [
              "command_name",
              "command_description"
            ],
            "properties": {
              "command_name": {
                "type": "string",
                "maxLength": 32
              },
              "command_description": {
                "type": "string",
                "maxLength": 256
              }
            },
            "additionalProperties": true
          }
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "enable_welcome_message",
      "prompts",
      "commands"
    ]
  },
  {
    "name": "set_webhook",
    "operationId": "setWebhook",
    "description": "Set the client webhook URL for inbound events.\n\n**Replaces** the stored webhook list with this single URL (it does not append).\nTo send to several endpoints, pass an array in `webhookUrl` or use `POST /settings`.\n\nWhatsApp **Calling** events (`field=calls`) are forwarded as passthrough\npayloads with `type: \"calls\"` and `instanceId` (connect / status / terminate).\nCall permission replies arrive on the normal messages path\n(`call_permission_reply`). Details: **Calling** tag.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "webhookUrl": {
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          ],
          "description": "Replacement webhook URL, or array of URLs (max 5)"
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "webhookUrl"
    ]
  },
  {
    "name": "set_whatsapp_business_encryption",
    "operationId": "setWhatsappBusinessEncryption",
    "description": "Upload and sign a 2048-bit RSA business public key (PEM) for this channel's phone number.\nMeta requires a signed key before Flow publish/send. Only one active key per number;\na new upload replaces the previous key.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "business_public_key": {
          "type": "string",
          "description": "2048-bit RSA public key in PEM format",
          "example": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA...\n-----END PUBLIC KEY-----\n"
        }
      },
      "additionalProperties": false,
      "required": [
        "business_public_key"
      ]
    },
    "inputFields": [
      "business_public_key"
    ]
  },
  {
    "name": "unblock_user",
    "operationId": "unblockUser",
    "description": "Unblock WhatsApp user",
    "inputSchema": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "phone"
      ]
    },
    "inputFields": [
      "phone"
    ]
  },
  {
    "name": "update_calling_settings",
    "operationId": "updateCallingSettings",
    "description": "Enable, disable, or update WhatsApp Calling settings (beta).\n\nProxies upstream `POST /calling/settings`.\nBody is forwarded as-is (1msg does not validate fields).\n\n**Common fields under `calling`**\n- `status` (`ENABLED` | `DISABLED`) — required to turn calling on/off\n- `call_icon_visibility` (`DEFAULT` | `DISABLE_ALL`) — optional\n- `callback_permission_status` (`ENABLED` | `DISABLED`) — optional;\n  when enabled, inbound user calls grant callback permission\n- `call_hours` — optional hours / timezone object\n- `sip` — optional SIP trunk; when SIP is ENABLED, Graph call actions and\n  calling webhooks are not used\n- `srtp_key_exchange_protocol` (`DTLS` | `SDES`) — SDES only with SIP\n- `video.status` — optional\n\nMeta may accept only one feature group per request — prefer focused updates\n(e.g. enable status first, then SIP).\n\nTrial / `subscriptionBlocked` → **403** plain text.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "calling": {
          "type": "object",
          "description": "Calling feature configuration for the business phone number",
          "properties": {
            "status": {
              "type": "string",
              "description": "Enable or disable Calling API on this number",
              "enum": [
                "ENABLED",
                "DISABLED"
              ],
              "example": "ENABLED"
            },
            "call_icon_visibility": {
              "type": "string",
              "description": "Controls call icon visibility in the WhatsApp client",
              "enum": [
                "DEFAULT",
                "DISABLE_ALL"
              ],
              "example": "DEFAULT"
            },
            "callback_permission_status": {
              "type": "string",
              "description": "When ENABLED, a user who calls your business automatically grants\ncall permission for business-initiated callbacks (subject to Meta rules).\n",
              "enum": [
                "ENABLED",
                "DISABLED"
              ],
              "example": "ENABLED"
            },
            "srtp_key_exchange_protocol": {
              "type": "string",
              "description": "SRTP key exchange. DTLS is default/recommended.\nSDES is only valid when SIP signaling is enabled.\n",
              "enum": [
                "DTLS",
                "SDES"
              ],
              "example": "DTLS"
            },
            "call_hours": {
              "type": "object",
              "description": "Optional call hours / timezone configuration (Meta shape)",
              "additionalProperties": true,
              "properties": {
                "status": {
                  "type": "string",
                  "example": "ENABLED"
                },
                "timezone": {
                  "type": "string",
                  "example": "America/Los_Angeles"
                },
                "day_of_week_start": {
                  "type": "string",
                  "example": "MONDAY"
                }
              }
            },
            "sip": {
              "type": "object",
              "description": "SIP trunk settings. When SIP is ENABLED, Graph call actions and\ncalling webhooks are not used — Meta dials your SIP server directly.\n",
              "properties": {
                "status": {
                  "type": "string",
                  "enum": [
                    "ENABLED",
                    "DISABLED"
                  ],
                  "example": "DISABLED"
                },
                "servers": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "hostname": {
                        "type": "string",
                        "example": "sip.example.com"
                      },
                      "port": {
                        "type": "integer",
                        "example": 5061
                      },
                      "request_uri_user_params": {
                        "type": "object",
                        "additionalProperties": {
                          "type": "string"
                        }
                      },
                      "sip_user_password": {
                        "type": "string",
                        "description": "Present on GET when SIP credentials are returned by Meta"
                      },
                      "password": {
                        "type": "string",
                        "description": "Alternate password field name from some Meta responses"
                      },
                      "app_id": {
                        "type": "string"
                      }
                    },
                    "additionalProperties": true
                  }
                }
              },
              "additionalProperties": true
            },
            "video": {
              "type": "object",
              "description": "Video calling toggle when supported",
              "properties": {
                "status": {
                  "type": "string",
                  "enum": [
                    "ENABLED",
                    "DISABLED"
                  ]
                }
              },
              "additionalProperties": true
            },
            "audio": {
              "type": "object",
              "description": "Audio settings (typically response-only)",
              "properties": {
                "status": {
                  "type": "string"
                }
              },
              "additionalProperties": true
            },
            "restrictions": {
              "type": "object",
              "description": "Calling restrictions (response-only)",
              "additionalProperties": true
            },
            "ip_addresses": {
              "type": "object",
              "description": "Meta media IP ranges (response-only)",
              "additionalProperties": true
            },
            "call_icons": {
              "type": "object",
              "description": "Call icon country restrictions (response-only)",
              "additionalProperties": true
            }
          },
          "additionalProperties": true
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "calling"
    ]
  },
  {
    "name": "update_me",
    "operationId": "updateMe",
    "description": "Update WhatsApp Business Account profile fields. At least one of\nabout, description, email, photo, address, vertical, websites is required.\nBlocked when the channel subscription limit is exceeded.\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "about": {
          "type": "string",
          "description": "Profile About section"
        },
        "address": {
          "type": "string"
        },
        "description": {
          "type": "string",
          "description": "Business description (max 256 characters)"
        },
        "email": {
          "type": "string"
        },
        "vertical": {
          "type": "string",
          "description": "Industry of the business"
        },
        "photo": {
          "type": "string",
          "description": "HTTPS URL or data:image/...;base64,... payload"
        },
        "websites": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false
    },
    "inputFields": [
      "about",
      "address",
      "description",
      "email",
      "vertical",
      "photo",
      "websites"
    ]
  }
];

export const GENERATED_MCP_TOOL_COUNT = GENERATED_MCP_TOOLS.length;
